name: Mantener Supabase activo

on:
  schedule:
    - cron: '0 12 */5 * *'
  workflow_dispatch:

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer ping a Supabase
        run: |
          curl -X GET "https://yyocuxxrybasrvsereuo.supabase.co/auth/v1/health"
